### PR TITLE
Added version symlinks: 0.x -> v0.x for compat

### PR DESCRIPTION
**Pull request by mbrukman**
Previously, URLs on docs.janusgraph.org were of the form:

* https://docs.janusgraph.org/0.1/
* https://docs.janusgraph.org/0.2/
* etc.

and with the new versions having the `v` prefix, all of those URLs are now
broken. This fixes it for all past docs (including docs that still need to be
published, such as the `0.1` and `0.4` series), as well as the upcoming version
`0.5`.

Signed-off-by: Misha Brukman <mbrukman@google.com>

### CODE REVIEW

**Comment by porunov** [comment]
@mbrukman any commit merged into this master branch will be removed and rewritten by Travis CI on the "deploy" stage. I don't know what happened with it and why half of the files are missing right now. The repository worked with `v0.2`, `v0.3`, `v0.4` and `master` branches. This is really strange. 
Nevertheless all commits for documentation should be directed into JanusGraph main repository, folder `docs`.

@farodin91 any thoughts on this? Do you know why some files were removed? It worked several hours ago and now some files are missing and `v0.4` is gone completely

**Comment by porunov** [comment]
@mbrukman Old urls will be broken even if we add symlinks because the structure of the documentation is changed. For example, there is now `Getting started` page because it was combined with `Introduction` page

**Comment by mbrukman** [comment]
If Travis is re-writing all of the pages destructively, then do we need to add `CNAME` and any other relevant files to the `/docs/` page of the JanusGraph repo? Will they get automatically copied over?

We could handle the symlinks the same way, assuming the deployment process will bring them over.

**Comment by porunov** [comment]
The deployment stage will be executed soon and all merged changes will be gone.
https://travis-ci.org/JanusGraph/janusgraph/builds/579203339?utm_source=github_status&utm_medium=notification

**Comment by porunov** [comment]
> If Travis is re-writing all of the pages destructively, then do we need to add CNAME and any other relevant files to the /docs/ page of the JanusGraph repo? Will they get automatically copied over?

Yes they will be copied. Also, the CNAME already exists: https://github.com/JanusGraph/janusgraph/tree/master/docs

**Comment by porunov** [comment]
It is really strange that the file was removed because there were no deployment scenario executed in the main repository after I have checked that everything works

**Comment by porunov** [comment]
@farodin91 
I am only thinking right now about the possibility to execute `deployment` stage in the fork repository. Can the `deployment` stage in a forked repository push changes into `JanusGraph/docs.janusgraph.org` repository?
For example, if this is a forked repository by someone who have the GITHUB_TOKEN?

**Comment by porunov** [comment]
@mbrukman I think after about 10-15 minutes (when deployment is executed here https://travis-ci.org/JanusGraph/janusgraph/builds/579203339?utm_source=github_status&utm_medium=notification) it should fix problems.

Do you have access to `janusgraph-bot` account? What if we generate `GITHUB_TOKEN` in that account and create branch protection so that ONLY janusgraph-bot can push commits into this repository? Will it work or I am missing something?

**Comment by porunov** [comment]
@mbrukman The deployment is executed and all files are back again. Everything works now.
We should investigate the problem.

@farodin91 Can we configure travis to execute deploy ONLY when if gets commits from janusgraph/janusgraph repository? And not from PRs.

**Comment by porunov** [comment]
I cannot currently find the problem. I don't know why half of the files were removed. I tried to remove some files in the forked repository and create a PR to master with removed CNAME.
I tried to execute deploy in a branch `v0.2` separately.
I tried to remove CNAME in a forked repository from all branches and execute build in that branches.

No changes were pushed into `docs.janusgraph.org` (which is good).

But, I've seen that some files were missing in this repository before. I have suspicious that the owner of the keys could somehow trigger incorrect deploy accidentally. Could be this a problem?

I think that the owner of the GITHUB_TOKEN should be `janusgraph_bot`. And only `janusgraph_bot` should have write access to this repository.

**Comment by farodin91** [comment]
@porunov i think the protection will work as the best Solution, if we use a janusgraph bot as token.

I will go through the Travis ci config to improve also protection.

**Pull request closed without merging**
